package com.example.workbycar.ui.navigation

sealed class AppScreens(val route: String) {
    object SplashScreen: AppScreens("splash_screen")
    object LogInScreen: AppScreens("log_in_screen")
    object SignUpScreen: AppScreens("sign_up_screen")
    object AddPhoneScreen: AppScreens("add_phone_screen")
    object MainScreen: AppScreens("main_screen")
    object PlaceSelectorScreen: AppScreens("place_slector_screen")
    object WeekSelectorScreen: AppScreens("week_selector_screen")
    object FoundTripsScreen: AppScreens("found_trips_screen")
    object TripInformationScreen: AppScreens("trip_information_screen")
    object MapScreen: AppScreens("map_screen")
    object TripsScreen: AppScreens("trips_screen")
    object ProfileScreen: AppScreens("profile_screen")
    object EditUserInfoScreen: AppScreens("edit_user_info_screen")
    object StartTripScreen: AppScreens("start_trip_screen")
    object OriginInMapScreen: AppScreens("origin_in_map_screen")
    object DestinationTripScreen: AppScreens("destination_trip_screen")
    object DestinationInMapScreen: AppScreens("destination_in_map_screen")
    object RouteSelectionScreen: AppScreens("route_selection_screen")
    object DateSelectionScreen: AppScreens("date_selection_screen")
    object DepartureTimeSelectionScreen: AppScreens("departure_time_selection_screen")
    object PassengersNumberScreen: AppScreens("passengers_number_screen")
    object ReservationTypeScreen: AppScreens("reservation_type_screen")
    object PriceRecommendationScreen: AppScreens("price_recommendation_screen")
    object PriceSelectorScreen: AppScreens("price_selector_screen")
    object TripPostingScreen: AppScreens("trip_posting_screen")
    object PublicationConfirmationScreen: AppScreens("publication_confirmation_screen")
    object MessagesScreen: AppScreens("messages_screen")
    object ChatScreen: AppScreens("chat_screen")

}