package com.example.workbycar.utils

object CountryCodes {

    val countryCodes = listOf(
        "Afghanistan (+93)",
        "Albania (+355)",
        "Algeria (+213)",
        "Andorra (+376)",
        "Angola (+244)",
        "Argentina (+54)",
        "Armenia (+374)",
        "Australia (+61)",
        "Austria (+43)",
        "Azerbaijan (+994)",
        "Bahamas (+1 242)",
        "Bahrain (+973)",
        "Bangladesh (+880)",
        "Belarus (+375)",
        "Belgium (+32)",
        "Belize (+501)",
        "Benin (+229)",
        "Bhutan (+975)",
        "Bolivia (+591)",
        "Bosnia and Herzegovina (+387)",
        "Botswana (+267)",
        "Brazil (+55)",
        "Brunei (+673)",
        "Bulgaria (+359)",
        "Burkina Faso (+226)",
        "Burundi (+257)",
        "Cambodia (+855)",
        "Cameroon (+237)",
        "Canada (+1)",
        "Chile (+56)",
        "China (+86)",
        "Colombia (+57)",
        "Congo (+242)",
        "Costa Rica (+506)",
        "Croatia (+385)",
        "Cuba (+53)",
        "Cyprus (+357)",
        "Czech Republic (+420)",
        "Denmark (+45)",
        "Dominican Republic (+1 809)",
        "Ecuador (+593)",
        "Egypt (+20)",
        "El Salvador (+503)",
        "Estonia (+372)",
        "Ethiopia (+251)",
        "Finland (+358)",
        "France (+33)",
        "Germany (+49)",
        "Greece (+30)",
        "Guatemala (+502)",
        "Honduras (+504)",
        "Hong Kong (+852)",
        "Hungary (+36)",
        "Iceland (+354)",
        "India (+91)",
        "Indonesia (+62)",
        "Iran (+98)",
        "Iraq (+964)",
        "Ireland (+353)",
        "Israel (+972)",
        "Italy (+39)",
        "Jamaica (+1 876)",
        "Japan (+81)",
        "Jordan (+962)",
        "Kazakhstan (+7)",
        "Kenya (+254)",
        "Kuwait (+965)",
        "Laos (+856)",
        "Latvia (+371)",
        "Lebanon (+961)",
        "Libya (+218)",
        "Lithuania (+370)",
        "Luxembourg (+352)",
        "Malaysia (+60)",
        "Mexico (+52)",
        "Mongolia (+976)",
        "Morocco (+212)",
        "Myanmar (+95)",
        "Nepal (+977)",
        "Netherlands (+31)",
        "New Zealand (+64)",
        "Nicaragua (+505)",
        "Nigeria (+234)",
        "North Korea (+850)",
        "Norway (+47)",
        "Oman (+968)",
        "Pakistan (+92)",
        "Panama (+507)",
        "Paraguay (+595)",
        "Peru (+51)",
        "Philippines (+63)",
        "Poland (+48)",
        "Portugal (+351)",
        "Qatar (+974)",
        "Romania (+40)",
        "Russia (+7)",
        "Saudi Arabia (+966)",
        "Serbia (+381)",
        "Singapore (+65)",
        "South Africa (+27)",
        "South Korea (+82)",
        "Spain (+34)",
        "Sri Lanka (+94)",
        "Sudan (+249)",
        "Sweden (+46)",
        "Switzerland (+41)",
        "Syria (+963)",
        "Taiwan (+886)",
        "Tanzania (+255)",
        "Thailand (+66)",
        "Tunisia (+216)",
        "Turkey (+90)",
        "Ukraine (+380)",
        "United Arab Emirates (+971)",
        "United Kingdom (+44)",
        "United States (+1)",
        "Uruguay (+598)",
        "Uzbekistan (+998)",
        "Venezuela (+58)",
        "Vietnam (+84)",
        "Yemen (+967)",
        "Zambia (+260)",
        "Zimbabwe (+263)"
    )

}